# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'TextureExample' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for TextureExample
  pod 'Texture'
  target 'TextureExampleTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'TextureExampleUITests' do
    # Pods for testing
  end

end
